services:
  api-financeiro-test:
    container_name: api-financeiro-test
    build:
      context: .docker/node/
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
    entrypoint: .docker/node/entrypoint.sh
    ports:
      - '3005:3005'
      - '7005:7005'
    volumes:
      - .:/home/node/app
    depends_on:
      db-financeiro-test:
        condition: service_healthy

  db-financeiro-test:
    container_name: db-financeiro-test
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    command: postgres -c log_statement=all -p 5005
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api-financeiro-test
    ports:
      - '5005:5005'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -p 5005']
      interval: 5s
      timeout: 5s
      retries: 5
